USE act_db;


SELECT empno, lastname, job,
	CASE 
		WHEN job IN('PRES','MANAGER') THEN "ADMIN FUNCTION"
        WHEN job IN('ANALYST','DESIGNER','OPERATIORS') THEN "OPERATIONAL FUNCTIONS"
        WHEN job IN('SALESREPS','FIELDREPS') THEN "SUPPORT FUNCTIONS"
        ELSE
			"COMPANY BRANCH FUNCTIONS"
		END AS "Company Functions"
FROM EMPLOYEE;