USE act_db;

ALTER TABLE DEPARTMENT
ADD FOREIGN KEY (mgrno) REFERENCES EMPLOYEE(empno);

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (workdept) REFERENCES DEPARTMENT(deptno);

ALTER TABLE DEPARTMENT
ADD FOREIGN KEY (admrdept) REFERENCES DEPARTMENT(deptno);

ALTER TABLE PROJECT
ADD FOREIGN KEY(respemp) REFERENCES EMPLOYEE(empno);

ALTER TABLE PROJECT
ADD FOREIGN KEY(deptno) REFERENCES DEPARTMENT(deptno);

ALTER TABLE EMP_ACT
ADD FOREIGN KEY(empno) REFERENCES EMPLOYEE(empno);

ALTER TABLE EMP_act
ADD FOREIGN KEY (projno) REFERENCES project(projno);