USE act_db;

ALTER TABLE EMPLOYEE
ADD COLUMN EMAIL VARCHAR(25),
ADD COLUMN CONTACT_PERSON VARCHAR(25),
ADD COLUMN CONTACT_PERSON_NO CHAR(11),
ADD COLUMN CONTACT_RELATIONSHIP VARCHAR(25),
ADD COLUMN CONTACT_ADDRESS VARCHAR(10),
ADD COLUMN CONTACT_JOB CHAR(11);


UPDATE EMPLOYEE
SET CONTACT_RELATIONSHIP = 'SPOUSE'
WHERE empno BETWEEN '000010' AND '200340';

SELECT * FROM EMPLOYEE;

DESCRIBE EMPLOYEE;
