USE act_db;


SELECT FORMAT(SUM(e.salary),2) AS "TOTAL-EMP-SALARY", FORMAT(AVG(e.salary),2) AS "AVERAGE-EMP-SALARY",FORMAT(MIN(e.salary),2) AS "SMALLEST-EMP-SALARY",
FORMAT(MAX(salary),2) AS "LARGEST-EMP-SALARY", COUNT(e.empno) AS "NO. OF EMPLOYEES", COUNT(d.deptno) AS "No. Of DEPT's"
FROM EMPLOYEE;